repos:
-   repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
    - id: black
      language_version: python3
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
    -   id: detect-private-key
    -   id: debug-statements
    -   id: check-yaml
    -   id: check-json
    -   id: check-docstring-first
    - id: check-added-large-files
